import type { Locale } from './i18n/locales'

const es = {
  "title": "Elegí dónde retirar",
  "mode": "Retiro en sucursal de Correo Argentino",
  "province": "Provincia de retiro",
  "search": "Localidad, código postal o sucursal",
  "searchHelp": "Elegí la zona que te quede cómoda, cerca de tu casa o trabajo.",
  "location": "Ordenar por cercanía a mi ubicación",
  "locationError": "No pudimos obtener tu ubicación. Podés buscar por localidad.",
  "loading": "Buscando sucursales…",
  "unavailable": "No pudimos cargar las sucursales. Conservamos tus datos: reintentá o escribinos para coordinar.",
  "retry": "Reintentar",
  "contact": "Consultar por email",
  "empty": "No encontramos sucursales para esa búsqueda. Probá otra localidad, quitá el filtro o elegí otra provincia.",
  "choose": "Elegir sucursal",
  "selected": "Sucursal elegida",
  "map": "Ver en el mapa",
  "distance": "km aprox. en línea recta",
  "more": "Mostrar más sucursales",
  "schedules": "Horarios informados por Correo",
  "noSchedules": "Consultá los horarios con la sucursal.",
  "days": "Lun,Mar,Mié,Jue,Vie,Sáb,Dom",
  "included": "Envío a sucursal incluido",
  "monthly": "Este importe de envío corresponde a cada entrega mensual.",
  "gift": "Es para otra persona",
  "recipient": "Nombre y apellido del destinatario",
  "identity": "Usá el nombre de quien recibirá el paquete. Para retirar tendrá que acreditar su identidad.",
  "review": "Revisá antes de pagar",
  "next": "Continuar",
  "back": "Volver",
  "product": "Producto",
  "total": "Total mensual a autorizar",
  "recurring": "Cobro automático mensual de este total, con envío incluido. La sucursal se usa para los próximos envíos; para cambiarla, respondé el email de confirmación antes del despacho.",
  "readyHelp": "Te avisaremos cuando lo despachemos. Consultá el seguimiento y esperá la confirmación de llegada antes de ir a retirar.",
  "changed": "La sucursal o la tarifa cambió. Volvé a elegir y revisá el resumen antes de pagar."
}
const en: typeof es = {
  "title": "Choose a pickup branch",
  "mode": "Pickup at a Correo Argentino branch",
  "province": "Pickup province",
  "search": "Town, postal code or branch",
  "searchHelp": "Choose a convenient area, near home or work.",
  "location": "Sort by distance from my location",
  "locationError": "We could not get your location. You can search by town.",
  "loading": "Finding branches…",
  "unavailable": "We could not load the branches. Your entered details are retained: retry or email us to arrange pickup.",
  "retry": "Retry",
  "contact": "Ask by email",
  "empty": "No branches match. Try another town, clear the filter or choose another province.",
  "choose": "Choose branch",
  "selected": "Selected branch",
  "map": "View on map",
  "distance": "km approx. in a straight line",
  "more": "Show more branches",
  "schedules": "Hours reported by Correo",
  "noSchedules": "Check opening hours with the branch.",
  "days": "Mon,Tue,Wed,Thu,Fri,Sat,Sun",
  "included": "Shipping to the branch included",
  "monthly": "This shipping amount applies to each monthly delivery.",
  "gift": "For someone else",
  "recipient": "Recipient full name",
  "identity": "Use the name of the person receiving the parcel. ID is required for pickup.",
  "review": "Review before paying",
  "next": "Continue",
  "back": "Back",
  "product": "Product",
  "total": "Monthly total to authorize",
  "recurring": "Automatic monthly payment of this total, including shipping. This branch is used for future deliveries; to change it, reply to the confirmation email before dispatch.",
  "readyHelp": "We will email you when it ships. Check tracking and wait for arrival confirmation before going to collect it.",
  "changed": "The branch or rate changed. Choose again and review before paying."
}

// International visitors retain an English fallback for the Argentina-only pickup flow.
export function pickupCopy(locale: Locale): typeof es { return locale === 'es' ? es : en }
